name: amiralrouge
favicon: null
layout_spectrum: 0.99761
typography_spectrum: 0.3762565611395985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02509a'
    - '#2079c9'
    - '#76b3d4'
    - '#aed4e3'
    - '#eae8e4'
  brandStrength: 0.02258679992519319
  lightness: 0.2751576160080731
  saturation: 0.8973368082661182
  rhythmicContrast: 0.8203438720665872
purpose: []
